FROM python:3.11.7-bullseye

RUN pip install poetry
RUN apt install -y git libpq-dev

ENV POETRY_NO_INTERACTION=1 \
    POETRY_VIRTUALENVS_IN_PROJECT=1 \
    POETRY_VIRTUALENVS_CREATE=1 \
    POETRY_CACHE_DIR=/tmp/poetry_cache

RUN git clone https://github.com/slashfast/mtech-test-backend.git
WORKDIR /mtech-test-backend
RUN poetry install && rm -rf $POETRY_CACHE_DIR
EXPOSE 8000
CMD ["poetry", "run", "python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0"]
